language: scala

services:
  - docker

scala:
  - 2.12.8

jdk:
  - oraclejdk8

jobs:
  include:
    - stage: test
      name: "test and report coverage"
      script: sbt clean coverage test coverageReport
      after_success: sbt coveralls
    - stage: deploy
      name: "build and push docker image"
      if: tag IS present
      script:
      - sbt -Ddocker.repository=zhongl -Ddocker.tag=$TRAVIS_TAG docker:publishLocal
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push zhongl/passport

notifications:
  email:
  - zhong.lunfu@gmail.com
