version: '3'
services:

  gateway:
    image: traefik:latest
    command:
      - "--api"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--docker"
      - "--docker.watch"
      - "--docker.domain=${DOMAIN}"
      - "--accesslog"
      - "--traefikLog"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - 80:80
        - 443:443

  passport:
    image: zhongl/passport:latest
    environment:
      JAVA_TOOL_OPTIONS: -Dconfig.file=/app.conf
      DOMAIN: $DOMAIN
    labels:
      traefik.port: 8080
      traefik.frontend.rule: "HostRegexp: {subdomain:[a-z]+}.${DOMAIN}"

  web:
    image: zhongl/passport:latest
    command:
      - "-e"
    environment:
      JAVA_TOOL_OPTIONS: -Dconfig.file=/app.conf
      DOMAIN: $DOMAIN
    labels:
      passport.forward.rule: "Host: www.${DOMAIN}"
      passport.forward.port: 8080
