version: '3'
services:

  passport:
    image: zhongl/passport:latest
    command:
      - "-d:docker"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JAVA_TOOL_OPTIONS: -Dconfig.file=/app.conf
      DOMAIN: $DOMAIN
    ports:
      - 80:8080

  web:
    image: zhongl/passport:latest
    command:
      - "-e"
    labels:
      passport.rule: "www.${DOMAIN} > :8080"
