version: '3.3'
services:

  gateway:
    image: traefik:latest
    command:
      - "--api"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--docker"
      - "--docker.watch"
      - "--docker.domain=${DOMAIN}"
      - "--accesslog"
      - "--traefikLog"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 443:443

  passport:
    image: zhongl/passport:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.port: 8080
      traefik.frontend.rule: "HostRegexp: {subdomain:[a-z]+}.${DOMAIN}"
    environment:
      JAVA_TOOL_OPTIONS: -Dconfig.file=/run/secrets/conf
      DOMAIN: $DOMAIN
    secrets:
      - conf

  echo:
    image: zhongl/passport:latest
    command:
      - "-e"
    labels:
      passport.rule: "www.${DOMAIN}"
      passport.port: 8080

secrets:
  conf:
    file: ./app.conf